<!DOCTYPE html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;color:#251b29;font-size:10px}h1{color:#43104a;font-size:20px;margin-bottom:5px}h2{font-size:12px;margin-top:22px}.muted{color:#666}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{padding:7px;border-bottom:1px solid #ddd;text-align:left}th{background:#f2eaf3}.summary td{width:50%}.right{text-align:right}
</style></head><body>
<h1>{{ $periodLabel }} Seller Report</h1>
<p>{{ $seller->sellerDetail?->business_name ?? $seller->name }}<br><span class="muted">{{ $start->format('M j, Y g:i A') }} – {{ $end->format('M j, Y g:i A') }} (Asia/Manila)<br>Generated {{ $generatedAt->format('M j, Y g:i A') }}</span></p>
<table class="summary"><tr><td>Gross product revenue</td><td class="right">PHP {{ number_format($stats['gross'], 2) }}</td></tr><tr><td>Delivered orders</td><td class="right">{{ number_format($stats['orders']) }}</td></tr><tr><td>Units sold</td><td class="right">{{ number_format($stats['units']) }}</td></tr><tr><td>Average order value</td><td class="right">{{ $stats['average'] === null ? '—' : 'PHP '.number_format($stats['average'], 2) }}</td></tr><tr><td>Shipping charged</td><td class="right">PHP {{ number_format($stats['shipping'], 2) }}</td></tr></table>
<p>Other outcomes in this period: {{ $outcomes['returned'] }} returned · {{ $outcomes['cancelled'] }} cancelled · {{ $outcomes['delivery_failed'] }} failed delivery.</p>
<h2>Top products</h2><table><thead><tr><th>Product</th><th>Units</th><th class="right">Product revenue</th></tr></thead><tbody>@forelse($topProducts as $item)<tr><td>{{ $item->product?->name ?? 'Unavailable product' }}</td><td>{{ $item->units_sold }}</td><td class="right">PHP {{ number_format($item->revenue, 2) }}</td></tr>@empty<tr><td colspan="3">No delivered products in this period.</td></tr>@endforelse</tbody></table>
<h2>Delivered orders</h2><p class="muted">First 100 orders shown. Totals above include every qualifying order.</p><table><thead><tr><th>Order</th><th>Delivered</th><th class="right">Product subtotal</th><th class="right">Shipping</th></tr></thead><tbody>@forelse($orders as $order)<tr><td>#{{ $order->number }}</td><td>{{ $order->delivered_at?->format('M j, Y') ?? '—' }}</td><td class="right">PHP {{ number_format($order->total_amount, 2) }}</td><td class="right">PHP {{ number_format($order->shipping_fee, 2) }}</td></tr>@empty<tr><td colspan="4">No delivered orders in this period.</td></tr>@endforelse</tbody></table>
<p class="muted">Product revenue is the stored order subtotal. It is not a payout or net earnings figure.</p>
</body></html>
