@php
    $beforePickup=in_array($order->status,['confirmed','preparing','ready_for_pickup']);
    $rider=$order->courier;
    $canTrack=!in_array($order->status,['delivered','completed','cancelled','returned']);
@endphp
<span class="ops-badge ops-badge--{{ $order->shipment_group }}">{{ \App\Models\Ecommerce\Order::SHIPMENT_LABELS[$order->shipment_group] }}</span>
<h3 class="ops-detail-number">{{ $order->number }}</h3>
<section class="ops-section"><h3>Order Information</h3><dl class="ops-info"><div><dt>Order ID</dt><dd>{{ $order->number }}</dd></div><div><dt>Order date</dt><dd>{{ $order->created_at->format('M j, Y g:i A') }}</dd></div><div><dt>Current stage</dt><dd>{{ $order->status_label }}</dd></div></dl></section>
<section class="ops-section"><h3>Customer Information</h3><dl class="ops-info"><div><dt>Customer name</dt><dd>{{ $order->buyer?->name??'Buyer unavailable' }}</dd></div><div><dt>Contact number</dt><dd>{{ $order->buyer?->phone_number??'Not provided' }}</dd></div><div class="ops-full"><dt>Delivery address</dt><dd>{{ $order->shipping_address?:'Not provided' }}</dd></div></dl></section>
<section class="ops-section"><h3>Tracking Information</h3><dl class="ops-info"><div><dt>Pickup courier</dt><dd>{{ $rider?->name??'Awaiting logistics assignment' }}</dd></div><div><dt>Delivery rider</dt><dd>{{ $order->deliveryCourier?->name??'Awaiting sorting and assignment' }}</dd></div><div><dt>Carrier</dt><dd>{{ $order->carrier_name?:'Not recorded' }}</dd></div><div class="ops-full"><dt>Vendo tracking reference</dt><dd class="ops-wrap">{{ $order->tracking_number }}</dd></div><div><dt>Carrier tracking no.</dt><dd class="ops-wrap">{{ $order->carrier_tracking_number?:'Not provided' }}</dd></div><div><dt>Estimated delivery</dt><dd>@if($order->estimated_delivery_from && $order->estimated_delivery_to){{ $order->estimated_delivery_from->format('M j, Y') }} – {{ $order->estimated_delivery_to->format('M j, Y') }}@else Not yet scheduled @endif</dd></div></dl></section>
<section class="ops-section"><h3>Ordered Items</h3><div class="ops-table-scroll"><table class="ops-table ops-table--small"><thead><tr><th>Product</th><th>Variation</th><th>Qty.</th><th>Unit price</th><th>Subtotal</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td><div class="ops-product">@include('seller.operations.image',['product'=>$item->product])<span>{{ $item->product?->name??'Product unavailable' }}</span></div></td><td>{{ implode(' / ',array_filter([$item->color,$item->size]))?:'—' }}</td><td>{{ $item->quantity }}</td><td>₱{{ number_format($item->price,2) }}</td><td>₱{{ number_format($item->quantity*$item->price,2) }}</td></tr>@endforeach</tbody></table></div>
    <dl class="ops-totals"><div><dt>Total items</dt><dd>{{ $order->items->sum('quantity') }}</dd></div><div><dt>Shipping fee</dt><dd>₱{{ number_format($order->shipping_fee,2) }}</dd></div><div><dt>Total amount</dt><dd>₱{{ number_format($order->total_amount,2) }}</dd></div></dl>
</section>
<section class="ops-section"><h3>Actions</h3>
    @if($beforePickup)
        <p class="ops-caption">{{ $order->status!=='ready_for_pickup'?'Finish preparation and mark this order ready for pickup in Orders.':'Ready for pickup. Waiting for logistics to assign a rider and for the rider to scan the parcel at pickup.' }} <a class="ops-text-link" href="{{ route('seller.orders.index',['order'=>$order->id]) }}">Open order</a></p>
        <details class="ops-action-details"><summary>Cancel Shipment</summary><form method="POST" action="{{ route('seller.shipments.update',$order) }}" data-operation class="ops-form">@csrf @method('PATCH')<input type="hidden" name="action" value="cancel"><input type="hidden" name="expected_status" value="{{ $order->status }}"><p class="ops-muted">This cancels the order before pickup, restores reserved stock, and notifies the buyer and assigned rider.</p><label>Cancellation reason<textarea name="reason" maxlength="500" required rows="3"></textarea></label><p class="ops-alert" data-form-error role="alert" hidden></p><button class="ops-button ops-button--danger">Confirm Cancellation</button></form></details>
    @else<p class="ops-muted">{{ in_array($order->status,['cancelled','returned','delivered','completed'])?'This shipment is closed.':'Pickup is complete. Further delivery stages are managed by logistics and the rider.' }}</p>@endif
    @if($order->canPrintShippingLabel())<a class="ops-button" href="{{ route('seller.orders.waybill',$order) }}" target="_blank" rel="noopener">Print Shipping Label</a>
    @elseif(in_array($order->status, ['confirmed', 'preparing', 'ready_for_pickup'], true))<button class="ops-button" type="button" disabled>Print Shipping Label</button><p class="ops-caption">{{ $order->status === 'ready_for_pickup' ? 'Waiting for pickup logistics assignment. Existing ready orders may need routing.' : 'Available after the order is ready for pickup and its pickup logistics is assigned.' }}</p>@endif
</section>
@if($canTrack)<details class="ops-action-details"><summary>Update Tracking Details</summary><form method="POST" action="{{ route('seller.shipments.tracking',$order) }}" data-operation class="ops-form">@csrf @method('PATCH')<input type="hidden" name="expected_status" value="{{ $order->status }}"><input type="hidden" name="expected_revision" value="{{ $order->revision }}"><p class="ops-caption">Record details supplied by your carrier. This does not change the assigned rider or shipping charge.</p><label>Carrier name<input name="carrier_name" maxlength="100" value="{{ $order->carrier_name }}"></label><label>Carrier tracking number<input name="carrier_tracking_number" maxlength="100" value="{{ $order->carrier_tracking_number }}"></label><div class="ops-form-grid"><label>Estimated delivery from<input type="date" name="estimated_delivery_from" value="{{ $order->estimated_delivery_from?->format('Y-m-d') }}"></label><label>Estimated delivery to<input type="date" name="estimated_delivery_to" value="{{ $order->estimated_delivery_to?->format('Y-m-d') }}"></label></div><p class="ops-alert" data-form-error role="alert" hidden></p><button class="ops-button">Save Tracking Details</button></form></details>@endif
<section class="ops-section"><h3>Shipment History</h3>@forelse($order->statusEvents as $event)<div class="ops-event"><strong>{{ \App\Models\Ecommerce\Order::STATUSES[$event->to_status]??$event->to_status }}</strong><small>{{ $event->created_at->format('M j, Y g:i A') }}</small>@if($event->note)<p>{{ $event->note }}</p>@endif</div>@empty<p class="ops-muted">No status events recorded for this order yet.</p>@endforelse</section>
