<x-seller.layout title="Shipments">
    @vite(['resources/css/seller/operations.css','resources/js/seller/operations.js'])
    <section class="ops-page">
        <header class="ops-page-head"><div><h1>Shipments</h1><p>Manage pickups and follow your orders through delivery.</p></div></header>
        <div class="ops-stats">
            @foreach(['all'=>['Total Shipments','shipments-icon.png'],'to_ship'=>['To Ship','to-pack-icon.png'],'in_transit'=>['In Transit','pending-deliveries-icon.png'],'delivered'=>['Delivered','completed-orders-icon.png']] as $key=>[$label,$icon])
                <a class="ops-stat" href="{{ route('seller.shipments.index',array_merge(request()->except(['page','status']),$key==='all'?[]:['status'=>$key])) }}"><span class="ops-stat-icon"><img src="{{ asset('assets/icons/seller/'.$icon) }}" alt=""></span><span>{{ $label }}<strong>{{ number_format($counts[$key]) }}</strong></span></a>
            @endforeach
        </div>
        <form method="GET" action="{{ route('seller.shipments.index') }}" class="ops-filters">
            <label class="ops-search"><span class="ops-sr-only">Search shipments</span><input type="search" name="search" value="{{ $filters['search']??'' }}" maxlength="100" placeholder="Search order ID, customer or tracking number…"></label>
            <label><span class="ops-sr-only">Shipment status</span><select name="status"><option value="">All statuses</option>@foreach(\App\Models\Ecommerce\Order::SHIPMENT_LABELS as $key=>$label)<option value="{{ $key }}" @selected(($filters['status']??'')===$key)>{{ $label }}</option>@endforeach</select></label>
            <details class="ops-date-filter"><summary>Date range @if(!empty($filters['date_from'])||!empty($filters['date_to'])) • @endif</summary><div><label>Order date from<input type="date" name="date_from" value="{{ $filters['date_from']??'' }}"></label><label>Order date to<input type="date" name="date_to" value="{{ $filters['date_to']??'' }}"></label><button type="submit" class="ops-button">Apply dates</button></div></details>
            <label><span class="ops-sr-only">Courier</span><select name="courier"><option value="">All couriers</option><option value="unassigned" @selected(($filters['courier']??'')==='unassigned')>Unassigned</option>@foreach($couriers as $courier)<option value="{{ $courier->id }}" @selected(($filters['courier']??'')==$courier->id)>{{ $courier->name }}</option>@endforeach</select></label>
            <button class="ops-button">Apply</button>@if(request()->query())<a class="ops-text-link" href="{{ route('seller.shipments.index') }}">Clear</a>@endif
        </form>
        @if(!empty($filters['date_from'])||!empty($filters['date_to']))<p class="ops-caption">Order dates: {{ $filters['date_from']??'Any' }} – {{ $filters['date_to']??'Any' }}</p>@endif
        <section class="ops-card ops-table-card" aria-label="Shipments"><div class="ops-table-scroll"><table class="ops-table ops-table--shipments"><thead><tr><th>Order ID</th><th>Customer</th><th>Items</th><th>Order date</th><th>Courier</th><th>Tracking no.</th><th>Status</th><th>Action</th></tr></thead><tbody>
            @forelse($shipments as $order)<tr data-record="{{ $order->id }}"><td class="ops-nowrap"><strong>{{ $order->number }}</strong></td><td>{{ $order->buyer?->name??'Buyer unavailable' }}<small class="ops-truncate" title="{{ $order->shipping_address }}">{{ $order->shipping_address?:'Address not provided' }}</small></td><td><div class="ops-product">@include('seller.operations.image',['product'=>$order->items->first()?->product])<small>{{ $order->items_sum_quantity??0 }} items</small></div></td><td class="ops-nowrap">{{ $order->created_at->format('M j, Y') }}<small>{{ $order->created_at->format('g:i A') }}</small></td><td>{{ $order->carrier_name ?: ($order->courier?->name??'Unassigned') }}@if($order->carrier_name)<small>{{ $order->courier?->name??'Rider not assigned' }}</small>@endif</td><td class="ops-tracking">{{ $order->carrier_tracking_number?:$order->tracking_number }}@unless($order->carrier_tracking_number)<small>Vendo reference</small>@endunless</td><td><span class="ops-badge ops-badge--{{ $order->shipment_group }}">{{ \App\Models\Ecommerce\Order::SHIPMENT_LABELS[$order->shipment_group] }}</span><small>{{ $order->status_label }}</small></td><td><div class="ops-row-actions"><a class="ops-button ops-button--small" href="{{ route('seller.shipments.show',$order) }}" data-panel data-panel-title="Shipment Details" data-record-id="{{ $order->id }}">View</a><details class="ops-menu"><summary aria-label="Actions for {{ $order->number }}">⋮</summary><div><a href="{{ route('seller.shipments.show',$order) }}" data-panel data-panel-title="Shipment Details">Details / tracking</a>@unless(in_array($order->status,['cancelled','returned']))<a href="{{ route('seller.orders.waybill',$order) }}" target="_blank" rel="noopener">Print label</a>@endunless</div></details></div></td></tr>@empty<tr><td colspan="8" class="ops-empty">No shipments match your filters. Accepted orders appear here.</td></tr>@endforelse
        </tbody></table></div>@include('seller.operations.pagination',['records'=>$shipments])</section>
        <div class="ops-bottom-panels">
            <section class="ops-card"><header class="ops-card-head"><h2>Shipment Overview</h2><a class="ops-text-link" href="{{ route('seller.shipments.index') }}">View all</a></header>
                @php
                    $colors=['to_ship'=>'#784080','in_transit'=>'#efa222','delivered'=>'#328453','cancelled'=>'#bb4545','returned'=>'#79818d'];
                    $cursor=0;$segments=[];
                    foreach($colors as $key=>$color){$end=$cursor+($counts['all']?$counts[$key]/$counts['all']*100:0);$segments[]=$color.' '.$cursor.'% '.$end.'%';$cursor=$end;}
                @endphp
                <div class="ops-chart-row"><div class="ops-donut" style="--chart: {{ $counts['all']?'conic-gradient('.implode(',',$segments).')':'#e5e1e5' }}" role="img" aria-label="{{ $counts['all'] }} shipments; breakdown listed alongside"><span>{{ $counts['all'] }}<small>shipments</small></span></div><ul class="ops-chart-key">@foreach(\App\Models\Ecommerce\Order::SHIPMENT_LABELS as $key=>$label)<li><a href="{{ route('seller.shipments.index',array_merge(request()->except('page'),['status'=>$key])) }}"><i style="background:{{ $colors[$key] }}" aria-hidden="true"></i><span>{{ $label }}<strong>{{ $counts[$key] }}</strong><small>{{ $counts['all']?number_format($counts[$key]/$counts['all']*100,1):0 }}%</small></span></a></li>@endforeach</ul></div>
                <p class="ops-caption">Counts follow search, order date and courier filters, across all statuses.</p>
            </section>
            <section class="ops-card"><header class="ops-card-head"><h2>Recent Shipments</h2><a class="ops-text-link" href="{{ route('seller.shipments.index',request()->except('page')) }}">View all</a></header>
                @forelse($recent as $order)<a class="ops-recent-row" href="{{ route('seller.shipments.show',$order) }}" data-panel data-panel-title="Shipment Details"><span class="ops-category-symbol" aria-hidden="true">↗</span><strong>{{ $order->number }}</strong><span>{{ $order->buyer?->name??'Buyer unavailable' }}</span><span class="ops-badge ops-badge--{{ $order->shipment_group }}">{{ \App\Models\Ecommerce\Order::SHIPMENT_LABELS[$order->shipment_group] }}</span><small>{{ $order->updated_at->format('M j, g:i A') }}</small></a>@empty<p class="ops-muted">No recent shipments for these filters.</p>@endforelse
            </section>
        </div>
    </section>
    @include('seller.operations.drawer')
</x-seller.layout>
