<x-admin.layout>
    <div class="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8">
        <div class="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-bold text-gray-900">Review Report</h1><p class="mt-1 text-sm text-gray-500">Report #{{ $report->id }} · {{ $report->created_at->format('M j, Y g:i A') }}</p></div><a href="{{ route('admin.review-reports.index') }}" class="rounded-lg border px-4 py-2 text-sm">Back to reports</a></div>
        @if(session('success'))<p class="mb-4 rounded-lg bg-green-50 p-3 text-sm text-green-800" role="status">{{ session('success') }}</p>@endif
        @if($errors->any())<p class="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</p>@endif
        <div class="grid gap-5 lg:grid-cols-3">
            <div class="space-y-5 lg:col-span-2">
                <section class="rounded-xl border bg-white p-5"><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold text-gray-900">Customer review</h2><p class="text-sm text-gray-500">{{ $report->review?->product?->name ?? 'Unavailable product' }} · Order #{{ $report->review?->order_id }}</p></div><span class="text-amber-500" aria-label="{{ $report->review?->rating }} out of 5 stars">{{ str_repeat('★', $report->review?->rating ?? 0) }}</span></div><p class="mt-4 whitespace-pre-line text-sm text-gray-700">{{ $report->review?->comment }}</p><p class="mt-3 text-xs text-gray-500">Buyer: {{ $report->review?->buyer?->name ?? 'Buyer' }}</p>@if($report->review?->reply)<div class="mt-4 border-l-2 border-[#3b1735] pl-3"><p class="text-sm font-medium">Seller response</p><p class="mt-1 whitespace-pre-line text-sm text-gray-600">{{ $report->review->reply->body }}</p></div>@endif</section>
                <section class="rounded-xl border bg-white p-5"><h2 class="font-semibold text-gray-900">Seller report</h2><p class="mt-3 whitespace-pre-line text-sm text-gray-700">{{ $report->reason }}</p><p class="mt-3 text-xs text-gray-500">Submitted by {{ $report->seller?->name ?? 'Seller' }}</p></section>
                <section class="rounded-xl border bg-white p-5"><h2 class="font-semibold text-gray-900">Moderation history</h2>@forelse($report->review?->moderationEvents ?? [] as $event)<div class="mt-3 border-l-2 border-gray-200 pl-3 text-sm"><p>{{ ucfirst($event->from_visibility) }} → {{ ucfirst($event->to_visibility) }}</p><p class="text-gray-600">{{ $event->reason }}</p><time class="text-xs text-gray-500">{{ $event->created_at->format('M j, Y g:i A') }}</time></div>@empty<p class="mt-2 text-sm text-gray-500">No moderation actions recorded.</p>@endforelse</section>
            </div>
            <aside class="space-y-5">
                <section class="rounded-xl border bg-white p-5"><h2 class="font-semibold text-gray-900">Review visibility</h2><p class="mt-1 text-sm text-gray-500">Current: {{ ucfirst($report->review?->visibility ?? 'unknown') }}</p><form method="POST" action="{{ route('admin.reviews.visibility', $report->review) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="visibility" value="{{ $report->review?->visibility === 'published' ? 'hidden' : 'published' }}"><label class="block text-sm">Reason<textarea name="reason" required minlength="10" maxlength="500" rows="4" class="mt-1 block w-full rounded-lg border-gray-300 text-sm" placeholder="Record why the visibility changed"></textarea></label><button class="w-full rounded-lg bg-[#3b1735] px-4 py-2 text-sm font-medium text-white">{{ $report->review?->visibility === 'published' ? 'Hide review' : 'Restore review' }}</button></form></section>
                <section class="rounded-xl border bg-white p-5"><h2 class="font-semibold text-gray-900">Report decision</h2><p class="mt-1 text-sm text-gray-500">Status: {{ ucfirst($report->status) }}</p>@if($report->status === 'open')<form method="POST" action="{{ route('admin.review-reports.resolve', $report) }}" class="mt-4 space-y-3">@csrf<label class="block text-sm">Decision<select name="status" class="mt-1 block w-full rounded-lg border-gray-300 text-sm"><option value="resolved">Resolve</option><option value="dismissed">Dismiss report</option></select></label><label class="block text-sm">Resolution note<textarea name="resolution_note" required minlength="10" maxlength="2000" rows="4" class="mt-1 block w-full rounded-lg border-gray-300 text-sm"></textarea></label><button class="w-full rounded-lg border border-[#6b4671] px-4 py-2 text-sm font-medium text-[#512258]">Save decision</button></form>@elseif($report->resolution_note)<p class="mt-3 whitespace-pre-line text-sm text-gray-700">{{ $report->resolution_note }}</p>@endif</section>
            </aside>
        </div>
    </div>
</x-admin.layout>
